export const MESSAGE_TYPES = {
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  CHAT_DELTA: 'CHAT_DELTA',
  RESET_CONVERSATION: 'RESET_CONVERSATION',
  CLEAR_ALL_CONVERSATIONS: 'CLEAR_ALL_CONVERSATIONS',
  GET_SETTINGS: 'GET_SETTINGS',
  TEST_JIRA_CONNECTION: 'TEST_JIRA_CONNECTION',
  TEST_LLM_CONNECTION: 'TEST_LLM_CONNECTION',
  GET_CHAT_CONTEXT: 'GET_CHAT_CONTEXT',
};
